### ISSUE TITLE
Slow Training

### ISSUE THREAD

**Issue by melih1996** [akashsengupta1997/STRAPS-3DHumanShapePose#13]
Hi, is it normal to have 4 hours/epoch during training. I have GTX 1070 and to complete even 100 epochs, I need 13 days. If so, how to improve it?

**Comment by akashsengupta1997** [comment]
Hi sorry for the late reply, unfortunately neural_mesh_renderer is rather slow - you can try using pytorch3d to render data instead (see https://github.com/akashsengupta1997/STRAPS-3DHumanShapePose/issues/14)
