### ISSUE TITLE
share the code for build SSP-3D

### ISSUE THREAD

**Issue by zhangzscn** [akashsengupta1997/STRAPS-3DHumanShapePose#20]
Hi ,thank for you wark.can you tell me where to find the code for build SSP-3D? Now only find  https://github.com/akashsengupta1997/SSP-3D but it only for visualisation and evaluation.

**Comment by akashsengupta1997** [comment]
Hi, sorry for the very late reply, this might be useful: https://github.com/akashsengupta1997/SSP-3D/issues/2
