### ISSUE TITLE
Mean SMPL parameters

### ISSUE THREAD

**Issue by ay4m** [akashsengupta1997/STRAPS-3DHumanShapePose#23]
How do you get the gender neutral mean smpl parameters i.e. the `neutral_smpl_mean_params_6dpose.npz` file?

**Comment by akashsengupta1997** [comment]
I believe I got them from here: https://github.com/nkolot/SPIN/tree/master/data 

They may originally be from the HMR repo.

**Comment by ay4m** [comment]
thanks
