### ISSUE TITLE
ssp-3d dataset

### ISSUE THREAD

**Issue by chenshudong** [akashsengupta1997/STRAPS-3DHumanShapePose#5]
hi,could you share the code about build the ssp-3d dataset?
thanks.

**Comment by akashsengupta1997** [comment]
ssp3d_code_messy.zip
<https://drive.google.com/file/d/1GlPdAwcEaWzhWUbaML3AnQBhcP6IuhdS/view?usp=drive_web>
Hi,

Sorry for the late reply! Unfortunately the optimisation code is not
cleaned up for release, but I have attached a zip file that should contain
all the parts that you need (losses, NMR renderer for optimisation, and
some other stuff), hopefully it is not too much of a pain to put it
together for it to work. The python package dependencies are the same as
for the STRAPS repo. Note that NMR is actually an outdated differentiable
renderer now and I would recommend moving over to pytorch3d (
https://github.com/facebookresearch/pytorch3d).

Akash
